# Generated by Django 3.1.3 on 2021-01-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
                ('author', models.CharField(blank=True, max_length=250, null=True)),
                ('results_by', models.CharField(blank=True, max_length=250, null=True)),
                ('type_of_pub', models.CharField(blank=True, max_length=250, null=True)),
                ('from_date', models.IntegerField(blank=True, null=True)),
                ('to_date', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
